### ISSUE TITLE
Style the overview page (HTML/CSS, Jekyll/Github-Pages)

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/intro#1]
The [Potsdam](https://coderdojopotsdam.github.io/intro/potsdam.html) and [Dahlem](https://coderdojopotsdam.github.io/intro/dahlem.html) page need some styling.

- the language sections could be more obviously divided
- the border/area of the tutorials could be more obvious

Hints:
- The potsdam and dahlem pages are generated using the [overview.html](https://github.com/CoderDojoPotsdam/intro/blob/master/_layouts/overview.html).
- When you do that, please keep in mind that we can not load content from the internet and the website must work offline, too.

If you need any help completing this pull-request, you can ask here or in the chat.

**Comment by questionmarcus** [comment]
Hi,

Was looking through some of the code and I was wondering what kind of styling you had in mind? Would you rather the current css files were edited or if some inline css was added to `overview.html`

**Comment by niccokunzmann** [comment]
Hi, good question. I like to split up styling and html. I did not 
research why that is a god idea in general.
I think: This way, the style can be re-used.
If you can, please put it into the css file.

**Comment by Mmgfrog** [comment]
Hello! This would be my first open source contribution.  Is it acceptable to View Source on overview.html and get to the external stylesheets that way? Or are the css files located elsewhere for forking/cloning?

**Comment by Mmgfrog** [comment]
Hi! This will be my first open source contribution and I am rusty on git but I will do my best. Thank you for creating a beginner-friendly issue. :)

**Comment by questionmarcus** [comment]
@Mmgfrog, I am currently working on this issue just now. Usually it is just one person working on an issue at a time.

**Comment by Mmgfrog** [comment]
You are doing all of the stylesheets for both Potsdam and Dahlem @questionmarcus ?

**Comment by questionmarcus** [comment]
it's the same issue, and I think the stylesheets are in the css/ directory - so yeah, working on both webpages.

**Comment by Mmgfrog** [comment]
@questionsmarcus OK well just so you know, this is still showing up as an open issue and it was not clear by the comment thread that you actually were working on this. you asked a question and that was it. Have fun!

**Comment by niccokunzmann** [comment]
Hi @questionmarcus and @Mmgfrog Welcome and great to see your interest in it.

@questionmarcus I think, you can not keep other people from contributing. Please share your progress in a pull request (You can put [WIP] in the title and "#1" in the comment). This allows other people to collaborate - as open-source is mostly about collaboration and transparency.

I.e. You and @Mmgfrog can work on the same repository and use the chat to make clear what you would like to do https://gitter.im/CoderDojoPotsdam/intro So, in the end, you two decide if you would like to work together on this one. I am just explaining the options you have.

Great to have you here :)

**Comment by niccokunzmann** [comment]
Also, this issue is quite broad: header footer, tutorial, section, offline-links, links, ... can be styled without having any conflicts with other people.

**Comment by niccokunzmann** [comment]
If you have questions or need help, you can let us know here.

**Comment by niccokunzmann** [comment]
@friedow Worked on this. We can close this.
#79 
#67
