### ISSUE TITLE
Create a folder for the dojo logos

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/intro#11]
The dojo logos can be loaded from the internet. However, we can also load them from the local repository.

1. create a folder in [/img](https://github.com/CoderDojoPotsdam/intro/tree/master/img/footer) named logos
2. copy in the images for CoderDojo Potsdam and Dahlem 
  - https://github.com/CoderDojoPotsdam/intro/blob/master/potsdam.html#L3
  - https://github.com/CoderDojoPotsdam/intro/blob/master/dahlem.html#L3
3. Change the lines above to "img/..." folder

**Comment by jccabrejas** [comment]
For reference, I had to try a few times. The path that finally works is

image: https://coderdojopotsdam.github.io/intro/img/logos/name_of_file.png
