### ISSUE TITLE
Document how to setup the repository

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/intro#19]
It should be documented in the [_docs](https://github.com/CoderDojoPotsdam/intro/tree/master/_docs) folder how to setup this website locally:

- install ruby
- install gem github-pages
- build the website with jekyll serve --trace

There are a lot of tutorials out there. Please choose some and add them to the documentation.
If you get the page to build locally, this is enough evidence that your tutorials worked.

If you have any questions, please ask.

**Comment by jccabrejas** [comment]
Hi, this seems to work for me

# Setting up repositories

- install ruby in Windows [→ visit][ruby]
  Assuming you have Windows 10 and bash on Ubuntu on Windows
  `sudo apt-get update -y && sudo apt-get upgrade -y`
  `sudo apt-add-repository ppa:brightbox/ruby-ng`
  `sudo apt-get update`
  `sudo apt-get install ruby2.3 ruby2.3-dev build-essential`
  `sudo gem update`
  `sudo gem install jekyll bundler`
  
  After all this, you can check if Jekyll is installed properly
  `jekyll -v`
- clone the repository
  If you don´t have git, create a folder, install git and clone the repository
  `mkdir ./CoderDojoIntro`
  `sudo apt-get install git`
  `git clone https://github.com/CoderDojoPotsdam/intro.git `  

- build the website (note the no-watch option, it didn´t work without it)
`jekyll serve --trace --no-watch`

See the page in http://localhost:4000
(note this is http, not https)

[ruby]: https://jekyllrb.com/docs/windows/

**Comment by niccokunzmann** [comment]
Yes, this looks ok. Would you like to create a pull request? I think, a file named setup.md in the_docs folder would be the location I expect this to be.

**Comment by niccokunzmann** [comment]
Closing this due to #77.
