### ISSUE TITLE
Add link to dojo page in header (HTML+Jekyll)

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/intro#36]
The pages of CoderDojo Potsdam and CoderDojo Dahlem both have titles in the header.
Allow clicking those titles to be redirected to the dojo page:

- https://coderdojopotsdam.github.io
- https://zen.coderdojo.com/dojos/de/institut-fuer-informatik-freie-universitaet/dahlem-freie-universitaet-berlin

Therefore:

- [x] Create a variable in the header of potsdam.html and dahlem.html named homepage
- [x] edit the _layouts/overview.html to access the homepage variable
- [x] add a link around image and heading
- [x] remove the styling from the link so that it is black again

You can start with point 1 and create a pull-request and do it step wise or do it all together. We will review your pull request and help if you have any questions.

**Comment by marqueslu** [comment]
Can i take this one?

**Comment by niccokunzmann** [comment]
@marqueslu Sure, you can. Please let us know if you need anything. If you share your progress as a pull request, others can come and collaborate.

**Comment by marqueslu** [comment]
@niccokunzmann  The first item is jus a varible? Or exists a function for this variable?

**Comment by niccokunzmann** [comment]
Thanks @marqueslu for add a link. 

Potsdam and Dahlem have different home pages. You can edit the front matter ( https://jekyllrb.com/docs/frontmatter/ ) of Potsdam and Dahlem to include these links. Have a look at how title is used and you can find out about how to use a possible url attribute. https://github.com/CoderDojoPotsdam/intro/blob/master/dahlem.html#L4

**Comment by dazyang** [comment]
We are doing an Open Source day today for our class. Can I also give this one a go?

**Comment by niccokunzmann** [comment]
@dazyang Sure, please go ahead.

**Comment by dazyang** [comment]
@niccokunzmann  Just submitted my pull request, cheers. :smiley:  #66

**Comment by niccokunzmann** [comment]
@dazyang, Thanks for your pull request. Closing this.
