### ISSUE TITLE
Add "report problem" to overview pages (HTML)

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/intro#52]
In order to improve the interaction with the users, please add a "report problem" to the footer of the page.

Hints:
 -  This should link to the issues, e.g. https://github.com/CoderDojoPotsdam/intro/issues/new
 - you can edit the file _layouts/overview.html

**Comment by davedodea** [comment]
Hi, I have submitted a [PR](https://github.com/CoderDojoPotsdam/intro/pull/54) for this issue. Thanks

**Comment by niccokunzmann** [comment]
We can close this. Thanks @davedodea :)
