### ISSUE TITLE
Add Spanish

### ISSUE THREAD

**Issue by jccabrejas** [CoderDojoPotsdam/intro#6]
Add spanish to list of languages to enable start making translations

**Comment by niccokunzmann** [comment]
You would need to edit this file to do so: https://github.com/CoderDojoPotsdam/intro/blob/master/_data/languages.yml

**Comment by jccabrejas** [comment]
I know which file to change. I forked the project but then I was not sure how to merge those changes.
https://github.com/jccabrejas/intro/commits/master

I show now as contributor, still getting my head around github and going through some of the training material.
